name: test-runner
'on':
  - workflow_dispatch 
jobs:
  oras-test:
    runs-on: self-hosted
    steps:
      - uses: ruchika-jain/hello-github-js-action@1.0.1
      - uses: ruchika-jain/hello-world-go-action@1.0.1
